name: Release
"on":
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        env:
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/main
          tag_with_ref: true
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}"
